- name: Deploy Dockerized App
  hosts: web
  become: true
  tasks:
    - name: Pull latest nginx image
      community.docker.docker_image:
        name: nginx
        source: pull

    - name: Run nginx container
      community.docker.docker_container:
        name: my_nginx
        image: nginx
        state: started
        ports:
          - "80:80"